@startmindmap
'https://plantuml.com/mindmap-diagram

@startmindmap

* Cotización

** Datos del cliente
*** Nombre
*** Información de contacto

** Producto o trabajo solicitado
*** Producto prefabricado
*** Producto personalizado
*** Cantidad

** Especificaciones del trabajo
*** Medidas
*** Diseño solicitado
*** Características requeridas
*** Requerimientos particulares del cliente

** Materiales
*** Tipo de material
*** Cantidad necesaria
*** Calibre del acero
*** Accesorios o piezas requeridas

** Precio
*** Precio del producto o trabajo
*** Costo considerado de los materiales
*** Mano de obra
*** Descuento si aplica
*** Precio final

** Condiciones de pago
*** 50% de anticipo
*** 50% contra entrega

** Tiempo de entrega
*** Tiempo estimado de fabricación
*** Fecha acordada con el cliente

** Entrega
*** Retiro por el cliente
*** Transporte si aplica

@endmindmap
