@startuml
'https://plantuml.com/activity-diagram-beta

start

:Se recibe un trabajo que requiere fabricación;
:Se determina la materia prima necesaria;
:Se verifica la materia prima disponible en el taller;

if (¿Hay suficiente materia prima?) then (Sí)

  :Se utiliza la materia prima disponible;
  :Continúa el proceso de producción;

else (No)

  :Se identifica la materia prima faltante;

  repeat
    :Se identifica un proveedor correspondiente;
    :Se contacta al proveedor o vendedor asignado;
    :Se consulta disponibilidad y precio del material;
  repeat while (¿El material está disponible?) is (No)

  :Se realiza el pedido o compra del material;
  :Se recibe o se retira la materia prima;
  :Se verifica el material recibido;
  :Se lleva la materia prima al taller;
  :Continúa el proceso de producción;

endif

stop

@enduml

@enduml
